"""Centralized layout constants for the Lisa boot launcher.

Every pixel position/size used anywhere in rendering.py or launcher.py
must come from here - no magic numbers elsewhere.

Everything below is a real screen pixel - there is no separate logical
canvas scaled up to the real display anymore (that indirection existed
so the launcher could adapt to whatever resolution was actually
connected, but caused more problems than it solved: a moire-prone
checkerboard that had to be special-cased to draw at native resolution
anyway, a colorkey/dual-surface trick just to composite it under the
scaled content, a mouse-coordinate conversion step, and a bitmap font
that only looked right because of the scale-up). This is a fixed design
for the real 1024x768 target panel; on a different-sized test monitor
the picker draws at this same fixed size/position rather than adapting,
which is an accepted tradeoff for the simplification.
"""

# The real output resolution this is designed for (the physical panel).
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

# Thin white strip across the very top of the screen.
TOP_STRIP_HEIGHT = 12

# The white diagnostic/selection panel.
PANEL_X = 48
PANEL_Y = 48
PANEL_WIDTH = 928
# Tall enough that an item's full footprint (label + gap + icon + gap +
# status, see rendering.draw_item's content_height) fits inside the
# panel's interior rect (panel inset by PANEL_CONTENT_INSET, then offset
# down by ITEMS_TOP_MARGIN) even in the worst case - a boot-diagnostic
# item with both a label and its completed-checkmark icon. With
# ICON_SIZE=128, CHECK_ICON_SIZE=48 and FONT_SCALE=2 that footprint is
# 14 (label, 7px glyph * scale 2) + 16 (gap) + 128 (icon) + 16 (gap) + 48
# (check) + 16 (padding) = 238px tall; 48 (ITEMS_TOP_MARGIN) + 238 + a
# little cushion, then + PANEL_CONTENT_INSET*2 rounds to 320.
PANEL_HEIGHT = 320
SHADOW_OFFSET = 6  # black drop-shadow offset, down and to the right

# Item (icon + label + status) layout inside the panel.
#
# ICON_SIZE went 48 -> 32 -> 48 -> 128, alongside dropping the
# logical-canvas scale-up above. Was chasing two different things across
# those changes: 32 was too small a pixel *budget* for detailed source
# art (confirmed directly - the NEXT icon's logo text was illegible
# noise at 32px, clean by 48px) independent of the doubling question;
# 128 is simply what "design directly for the real 1024px-wide screen,
# no 2x step" calls for at the same on-screen size 48 was giving after
# doubling (48 logical * 2x real = 96 real - 128 goes a further step up
# for extra detail headroom now that there's no scale-up softening it).
ICON_SIZE = 128         # icons are square, ICON_SIZE x ICON_SIZE real px - matches the real
                        # 128x128 PNG assets (imported from high-res source art via import_icons.py,
                        # or procedurally generated by gen_icons.py as a fallback placeholder)
# Smaller "completed" checkmark badge shown under a finished diag item.
# Not tied to ICON_SIZE by a fixed ratio - just comfortably above the
# ~20-24px floor (at the old logical scale) where the check-mark source
# art's thin diagonal stroke started visibly breaking into dots.
CHECK_ICON_SIZE = 48
# Horizontal distance between item centers. At ICON_SIZE=128 this leaves
# 176-128=48px of gap between adjacent icons' edges.
ICON_SPACING = 176
ITEMS_TOP_MARGIN = 48   # vertical offset from panel top to the icon row

# Row-wrapping: beyond ITEMS_PER_ROW items, the picker wraps onto
# additional rows rather than overflowing the panel or shrinking icons.
# PANEL_WIDTH(928) - PANEL_CONTENT_INSET*2(16) = 912px of interior width;
# floor(912 / ICON_SPACING(176)) = 5 items fit one row - exactly this
# project's current system count, with a 6th wrapping to a second row.
ITEMS_PER_ROW = 5
# An item footprint's content height in the worst case (label + gap +
# icon + status present) - see draw_item's content_height, and the
# PANEL_HEIGHT derivation above for the arithmetic (238). Used to space
# additional rows a fixed distance apart regardless of whether a given
# row's items happen to have status text.
ITEM_ROW_HEIGHT = 238
ITEMS_ROW_GAP = 16      # vertical gap (px) between item rows

# Bitmap font scale: the 5x7 glyphs are drawn with each glyph pixel as a
# FONT_SCALE x FONT_SCALE block. Now load-bearing for legibility - with
# no logical->real scale-up to rely on anymore, text drawn at scale 1
# would be tiny (a 5px-wide "I" on a real 1024px-wide screen).
FONT_SCALE = 2

# Boot diagnostic animation timing. Slow enough that each step is
# actually visible during a real boot, not just a flicker.
BOOT_DIAG_STEP_SECONDS = 0.6

# Rendering layout constants (rendering.py must not introduce its own
# magic numbers - every literal used for positioning/sizing belongs here).
PANEL_CONTENT_INSET = 16   # inset (px, each side) from panel_rect to its interior content rect
ITEM_CONTENT_PADDING = 16  # padding (px) added around an item's icon/label/status when sizing its footprint
ITEM_ELEMENT_GAP = 16      # vertical gap (px) between an item's label/icon/status elements
# Minimum width (px) subtracted from ICON_SPACING to floor an item's
# reverse-video footprint width, so short labels (e.g. "MEM") still get a
# properly sized selection box instead of one that hugs just the icon.
ITEM_MIN_WIDTH_SLACK = 32
HEADER_LINE_GAP = 4        # vertical gap (px) between the panel's two header text lines

# Checkerboard background cell size, in real screen pixels - it's drawn
# directly at the real screen's own resolution (never scaled), so this
# was always a real-pixel size, unaffected by the logical-canvas removal
# above; see rendering.draw_checkerboard.
CHECKER_CELL_SIZE = 2
