"""Centralized layout constants for the Lisa boot launcher.

Every pixel position/size used anywhere in rendering.py or launcher.py
must come from here - no magic numbers elsewhere.
"""

# Real output resolution (the physical panel)
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

# Logical render resolution - everything is drawn here, then
# nearest-neighbor scaled up to SCREEN_WIDTH x SCREEN_HEIGHT.
LOGICAL_WIDTH = 512
LOGICAL_HEIGHT = 384

# Thin white strip across the very top of the logical surface.
TOP_STRIP_HEIGHT = 6

# The white diagnostic/selection panel.
PANEL_X = 32
PANEL_Y = 24
PANEL_WIDTH = 448
# Tall enough that an item's full footprint (label + gap + icon + gap +
# status, see rendering.draw_item's content_height) fits inside the
# panel's interior rect (panel inset by PANEL_CONTENT_INSET, then offset
# down by ITEMS_TOP_MARGIN) even in the worst case - a boot-diagnostic
# item with both a label and its completed-checkmark icon. With
# ICON_SIZE=48 and CHECK_ICON_SIZE=24 that footprint is 7 (label) + 4
# (gap) + 48 (icon) + 4 (gap) + 24 (check) + 8 (padding) = 95px tall;
# 28 (ITEMS_TOP_MARGIN) + 95 + a few px of cushion, then
# + PANEL_CONTENT_INSET*2 rounds to 140.
PANEL_HEIGHT = 140
SHADOW_OFFSET = 3  # black drop-shadow offset, down and to the right

# Item (icon + label + status) layout inside the panel.
ICON_SIZE = 48          # icons are square, ICON_SIZE x ICON_SIZE logical px - matches the real
                        # 48x48 PNG assets (imported from high-res source art via import_icons.py,
                        # or procedurally generated by gen_icons.py as a fallback placeholder)
# Smaller "completed" checkmark badge shown under a finished diag item.
# 24 is close to the minimum that survives the source art's thin diagonal
# stroke through LANCZOS downscale + hard black/white threshold without
# visibly breaking up into dots (confirmed by rendering several sizes).
CHECK_ICON_SIZE = 24
ICON_SPACING = 96       # horizontal distance between item centers
ITEMS_TOP_MARGIN = 28   # vertical offset from panel top to the icon row

# Row-wrapping: beyond ITEMS_PER_ROW items, the picker wraps onto
# additional rows rather than overflowing the panel or shrinking icons.
# PANEL_WIDTH(448) - PANEL_CONTENT_INSET*2(8) = 440px of interior width;
# floor(440 / ICON_SPACING(96)) = 4 items comfortably fit one row (a 5th
# item's footprint overhangs past the panel edge - the bug this fixes).
ITEMS_PER_ROW = 4
# An item footprint's content height with the largest case (label + gap +
# icon + status present) - see draw_item's content_height: 7 (label) + 4
# (gap) + 48 (icon) + 4 (gap) + 7 (status) + 8 (padding) = 78. Used to
# space additional rows a fixed distance apart regardless of whether a
# given row's items happen to have status text.
ITEM_ROW_HEIGHT = 78
ITEMS_ROW_GAP = 8       # vertical gap (px) between item rows

# Bitmap font scale: 1 logical pixel per font pixel (the font itself is
# already small - 5x7 - so no additional scale is applied at the logical
# resolution; the 2x logical->real scale-up is what makes it look
# authentically chunky on the real screen).
FONT_SCALE = 1

# Boot diagnostic animation timing. Slow enough that each step is
# actually visible during a real boot, not just a flicker.
BOOT_DIAG_STEP_SECONDS = 0.6

# Rendering layout constants (rendering.py must not introduce its own
# magic numbers - every literal used for positioning/sizing belongs here).
PANEL_CONTENT_INSET = 4    # inset (px, each side) from panel_rect to its interior content rect
ITEM_CONTENT_PADDING = 8   # padding (px) added around an item's icon/label/status when sizing its footprint
ITEM_ELEMENT_GAP = 4       # vertical gap (px) between an item's label/icon/status elements
# Minimum width (px) subtracted from ICON_SPACING to floor an item's
# reverse-video footprint width, so short labels (e.g. "MEM") still get a
# properly sized selection box instead of one that hugs just the icon.
ITEM_MIN_WIDTH_SLACK = 16
HEADER_LINE_GAP = 2        # vertical gap (px) between the panel's two header text lines

# Checkerboard background cell size, in real screen pixels - it's drawn
# directly at the real screen's own resolution (never scaled), so this is
# deliberately a real-pixel size rather than a logical one; see
# rendering.draw_checkerboard.
CHECKER_CELL_SIZE = 4
