"""Centralized layout constants for the Lisa boot launcher.

Every pixel position/size used anywhere in rendering.py or launcher.py
must come from here - no magic numbers elsewhere.

Everything below is a real screen pixel - there is no separate logical
canvas scaled up to the real display anymore (that indirection existed
so the launcher could adapt to whatever resolution was actually
connected, but caused more problems than it solved). This is a fixed
design for the real 1024x768 target panel; on a different-sized test
monitor the picker draws at this same fixed size/position rather than
adapting, which is an accepted tradeoff for the simplification.

Layout (2026-09-25 redesign, "CHOOSE YOUR ADVENTURE" card grid): a
single cream panel holds a title, a rule, a row of bordered item cards
(icon + name + subtitle each), a second rule, and a footer hint row.
There is no separate top strip anymore - the checkerboard fills the
whole screen behind the one panel.
"""

# The real output resolution this is designed for (the physical panel).
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

# The panel. PANEL_HEIGHT/PANEL_Y (bottom of this file) are derived for
# the common single-row (5-system) case - see the arithmetic there.
PANEL_X = 48
PANEL_WIDTH = 928
SHADOW_OFFSET = 6  # black drop-shadow offset, down and to the right

# Inset (px, EACH side) from the panel's outer rect to its interior
# content rect - rendering.panel_interior_rect() applies this directly
# (not via Rect.inflate(), whose halving-per-side semantics previously
# made this constant's "each side" doc comment inaccurate).
PANEL_CONTENT_INSET = 32

# Icons are square, ICON_SIZE x ICON_SIZE real px - matches the real
# 128x128 PNG assets (imported from high-res source art via
# import_icons.py, or procedurally generated by gen_icons.py as a
# fallback placeholder). Unchanged by the 2026-09-25 redesign - reused
# as-is rather than regenerating every icon asset at a new size.
ICON_SIZE = 128
# Smaller "completed" checkmark badge - only used by the boot-diagnostic
# item flow, which is currently disabled (not called from launcher.py)
# but kept working/tested in boot_diag.py for a possible future re-add.
CHECK_ICON_SIZE = 48

# Item cards. ITEM_BOX_WIDTH + the horizontal pitch below are chosen so
# 5 cards (this project's current system count) exactly fill the
# panel's interior width with a small gap between adjacent cards - see
# the arithmetic at the bottom of this file.
ITEM_BOX_WIDTH = 160
# Horizontal distance between card centers - leaves
# ICON_SPACING - ITEM_BOX_WIDTH = 16px of gap between adjacent cards.
ICON_SPACING = 176
ITEMS_PER_ROW = 5
ITEMS_ROW_GAP = 16  # vertical gap (px) between rows, if more than ITEMS_PER_ROW systems exist

# A card's internal vertical layout: padding, then icon, then name, then
# subtitle, then padding.
ITEM_BOX_PADDING_TOP = 24
ITEM_BOX_ICON_NAME_GAP = 16
ITEM_BOX_NAME_SUBTITLE_GAP = 10
ITEM_BOX_PADDING_BOTTOM = 20
# Card height: 24 (pad top) + 128 (icon) + 16 (icon->name gap) + 14
# (name, 7px glyph * FONT_SCALE 2) + 10 (name->subtitle gap) + 7
# (subtitle, 7px glyph * SUBTITLE_FONT_SCALE 1) + 20 (pad bottom) = 219.
ITEM_ROW_HEIGHT = 219

# Bitmap font scale: the 5x7 glyphs are drawn with each glyph pixel as an
# N x N block. FONT_SCALE is used for the title, card names, and footer
# hints; SUBTITLE_FONT_SCALE (smaller, unscaled) is used only for each
# card's subtitle line, to match the visual size contrast in the design.
FONT_SCALE = 2
SUBTITLE_FONT_SCALE = 1

# The two horizontal rules (below the title, below the card grid) and
# the gaps around them.
RULE_THICKNESS = 2
HEADER_RULE_GAP = 16     # title bottom -> first rule
RULE_TO_GRID_GAP = 24    # first rule -> card grid top
GRID_TO_RULE_GAP = 24    # card grid bottom -> second rule
RULE_TO_FOOTER_GAP = 16  # second rule -> footer text

# SHUT DOWN/QUIT are now individually clickable buttons (not just a
# static hint string), each with its own hover-highlight/hit-test rect.
FOOTER_BUTTON_GAP = 24  # horizontal gap between the SHUT DOWN and QUIT buttons
FOOTER_BUTTON_PADDING = 8  # padding around each button's text, both axes

# The SHUT DOWN/QUIT confirmation dialog, a fixed-size box centered on
# the screen (not the panel) - deliberately simple/fixed rather than
# derived from the panel's own geometry, since it only ever shows a
# short message and two buttons.
CONFIRM_DIALOG_WIDTH = 480
CONFIRM_DIALOG_HEIGHT = 200
CONFIRM_DIALOG_MESSAGE_TOP_GAP = 40    # dialog top -> message text
CONFIRM_DIALOG_BUTTONS_BOTTOM_GAP = 64  # dialog bottom -> buttons row
CONFIRM_BUTTON_GAP = 48    # horizontal gap between CONFIRM and CANCEL
CONFIRM_BUTTON_PADDING = 10  # padding around each button's text, both axes

# Boot diagnostic animation timing - unused while the diagnostic phase is
# disabled in launcher.py, kept for boot_diag.py's own tests/possible
# future re-add.
BOOT_DIAG_STEP_SECONDS = 0.6

# Checkerboard background cell size, in real screen pixels - drawn
# directly at the real screen's own resolution (never scaled), so this
# is unaffected by the panel-layout redesign above.
CHECKER_CELL_SIZE = 2

# Panel height for the single-row (5-system) case - rendering._panel_height()
# adds ITEM_ROW_HEIGHT + ITEMS_ROW_GAP per row beyond the first. Chrome
# (everything except the card grid) = 32 (top inset) + 14 (title) + 16
# (title->rule gap) + 2 (rule) + 24 (rule->grid gap) + 24 (grid->rule
# gap) + 2 (rule) + 16 (rule->footer gap) + 14 (footer) + 32 (bottom
# inset) = 176. PANEL_HEIGHT = 176 + ITEM_ROW_HEIGHT(219) = 395.
PANEL_HEIGHT = 395
# Centered in the 768px screen: (768 - 395) // 2 = 186.
PANEL_Y = 186
